 let Deck = [
  { card: "A", type: "♠" },
  { card: 2, type: "♠" },
  { card: 3, type: "♠" },
  { card: 4, type: "♠" },
  { card: 5, type: "♠" },
  { card: 6, type: "♠" },
  { card: 7, type: "♠" },
  { card: 8, type: "♠" },
  { card: 9, type: "♠" },
  { card: 10, type: "♠" },
  { card: "K", type: "♠" },
  { card: "Q", type: "♠" },
  { card: "J", type: "♠" },
  { card: "A", type: "♥" },
  { card: 2, type: "♥" },
  { card: 3, type: "♥" },
  { card: 4, type: "♥" },
  { card: 5, type: "♥" },
  { card: 6, type: "♥" },
  { card: 7, type: "♥" },
  { card: 8, type: "♥" },
  { card: 9, type: "♥" },
  { card: 10, type: "♥" },
  { card: "K", type: "♥" },
  { card: "Q", type: "♥" },
  { card: "J", type: "♥" },
  { card: "A", type: "🔹" },
  { card: 2, type: "🔹" },
  { card: 3, type: "🔹" },
  { card: 4, type: "🔹" },
  { card: 5, type: "🔹" },
  { card: 6, type: "🔹" },
  { card: 7, type: "🔹" },
  { card: 8, type: "🔹" },
  { card: 9, type: "🔹" },
  { card: 10, type: "🔹" },
  { card: "K", type: "🔹" },
  { card: "Q", type: "🔹" },
  { card: "J", type: "🔹" },
  { card: "A", type: "🍀" },
  { card: 2, type: "🍀" },
  { card: 3, type: "🍀" },
  { card: 4, type: "🍀" },
  { card: 5, type: "🍀" },
  { card: 6, type: "🍀" },
  { card: 7, type: "🍀" },
  { card: 8, type: "🍀" },
  { card: 9, type: "🍀" },
  { card: 10, type: "🍀" },
  { card: "K", type: "🍀" },
  { card: "Q", type: "🍀" },
  { card: "J", type: "🍀" },

];
export default Deck
